services:
  rtsp2hls:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./hls_output:/app/hls_output
      - .:/app
    restart: unless-stopped
    entrypoint:
      - go
    command:
      - run
      - cmd/convert/main.go
    networks:
      - rtsp_network


  file_server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "6001:6001"
    volumes:
      - ./hls_output:/app/hls_output
    depends_on:
      - rtsp2hls
    networks:
      - rtsp_network
    entrypoint:
      - go
    command:
      - run
      - cmd/file_server/main.go

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./hls_output:/app/hls_output
      - .:/app
    restart: unless-stopped
    ports:
      - "8080:8080"
    entrypoint:
      - go
    command:
      - run
      - cmd/api/main.go
    networks:
      - rtsp_network

networks:
  rtsp_network:
    driver: bridge